# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-ffprobe}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Philip Garrett"]
  s.date = %q{2010-06-12}
  s.description = %q{= FFProbe - ffprobe wrapper for Ruby

FFprobe is a simple multimedia streams analyzer with a command-line
interface based on the FFmpeg project libraries.  This is a ruby
interface to that command-line program.

== You will need

* A working Ruby installation
* A working ffprobe installation (http://sourceforge.net/projects/ffprobe/)
* A sane build environment

== Author

* Philip Garrett <philgarr at gmail.com>

== Copyright and License

Copyright (c) 2010 Philip Garrett.

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be included
in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
}
  s.email = %q{philgarr@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/ffprobe.rb",
     "lib/ffprobe/entity.rb",
     "lib/ffprobe/file_info.rb",
     "lib/ffprobe/frame_info.rb",
     "lib/ffprobe/packet_info.rb",
     "lib/ffprobe/parser.rb",
     "lib/ffprobe/result.rb",
     "lib/ffprobe/safe_pipe.rb",
     "lib/ffprobe/stream_info.rb",
     "lib/ffprobe/tags_info.rb",
     "lib/ffprobe/unit.rb",
     "test/ffprobe/test_ffprobe.rb",
     "test/ffprobe/test_file_info.rb",
     "test/ffprobe/test_parser.rb",
     "test/helper.rb",
     "test/test_result.rb",
     "test/testcases/files.testcase",
     "test/testcases/files_streams_tags.testcase",
     "test/testcases/frames.testcase",
     "test/testcases/no_args.testcase",
     "test/testcases/packets.testcase",
     "test/testcases/pretty_files.testcase",
     "test/testcases/pretty_files_streams_tags.testcase",
     "test/testcases/pretty_frames.testcase",
     "test/testcases/pretty_packets.testcase",
     "test/testcases/pretty_streams.testcase",
     "test/testcases/pretty_tags.testcase",
     "test/testcases/streams.testcase",
     "test/testcases/tags.testcase"
  ]
  s.homepage = %q{http://github.com/kingpong/ruby-ffprobe}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ruby wrapper for FFprobe multimedia analyzer}
  s.test_files = [
    "test/ffprobe/test_ffprobe.rb",
     "test/ffprobe/test_file_info.rb",
     "test/ffprobe/test_parser.rb",
     "test/helper.rb",
     "test/test_result.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

